### ISSUE TITLE
Venue address not populating on map

### ISSUE THREAD

**Issue by annemnichols** [AmandaWalter/WhereArtThou#77]
KKKKHHHHHHHAAAAAAANNNNNN-rad.

**Comment by KonradMaurer22** [comment]
Map fixes to do:
- change venue names to camel case
- don't use url for icons
- Add events to map with distinct icons

optional: 
- Add list of all nearby venues
  --- Make them pan to the venue on the map

**Comment by KonradMaurer22** [comment]
Make sure GMaps isn't unnessessarilly loading unseen on other pages.
